#!/bin/bash

TERNOA_VERSION="1.3.2"
TERNOA_ENV="mainnet"

DOWNLOAD_URL="https://github.com/capsule-corp-ternoa/ternoa-node/releases/download/v${TERNOA_VERSION}/ternoa"

_divider="--------------------------------------------------------------------------------"
_prompt=">>>"
_indent="   "

validator_name=""

cat 1>&2 <<EOF
                                  Welcome to TERNOA installer 

$_divider
Website: https://ternoa.com
Docs: https://ternoa-2.gitbook.io/ternoa-testnet-guide/
Support : https://ternoahelp.zendesk.com/hc/en-150
$_divider

EOF

echo "$_prompt We'll be installing Ternoa via a pre-built archive at ${DOWNLOAD_URL}/"

# Check architecture
if [ $(arch) != "x86_64" ]; then
    echo "$_prompt This binary can only be run on x86 architecture."
    echo "$_prompt Exiting..."
    exit 1
fi

# Pre-requisites installation
echo "$_prompt Installing pre-requisites..."
sudo apt update
sudo apt install build-essential git cmake protobuf-compiler -y
echo "$_prompt Pre-requisites installed successfully."

PS3='Please choose the ternoa chain environment: '
select opt in Alphanet Mainnet
do
    case $opt in
        Alphanet)
            echo "Connecting to Mainnet ...";
            TERNOA_ENV="alphanet"; break
            ;;
        Mainnet)
            echo "Connecting to Mainnet ...";
            TERNOA_ENV="mainnet";  break
            ;;
        *) 
            echo "invalid option $REPLY"; 
            exit 1 
            ;;   
    esac
done

while true; do
    read -rp "Enter Your Validator Name: " validator_name  </dev/tty
    if [[ ! -z "$validator_name" ]] ; then
        break ;
    fi
done

# Download Ternoa binary
sudo wget "$DOWNLOAD_URL" -O /usr/bin/ternoa
sudo chmod +x "/usr/bin/ternoa"

# Create directory for Ternoa node data
sudo mkdir -p "/opt/ternoa/node-data"

# Create systemd service file
sudo tee /etc/systemd/system/ternoa.service > /dev/null <<EOT
[Unit]
Description=Ternoa Validator Node By Ternoa.com

[Service]
ExecStart=/usr/bin/ternoa --name ${validator_name} --chain ${TERNOA_ENV} --base-path /opt/ternoa/node-data --ws-max-connections 1000 --prometheus-port 9615 --validator --telemetry-url "wss://telemetry.polkadot.io/submit/ 0" --state-pruning archive
WorkingDirectory=/usr/bin
KillSignal=SIGINT
Restart=on-failure
LimitNOFILE=10240
SyslogIdentifier=ternoa

[Install]
WantedBy=multi-user.target
EOT

# Reload systemd and start Ternoa service
sudo systemctl daemon-reload
sudo systemctl enable ternoa
sudo systemctl start ternoa

printf "%s Install succeeded!\n" "$_prompt"
printf "\n"
printf "%s You can restart ternoa service using : systemctl restart ternoa\n"
printf "%s You can get the status of ternoa service using : systemctl status ternoa\n"
printf "%s You can stop ternoa service using : systemctl stop ternoa\n"
printf "\n"
printf "%s More information at https://ternoa-2.gitbook.io/ternoa-testnet-guide/\n" "$_prompt"
